### ISSUE TITLE
调研testbird, 网易的pomelo-robot框架

### ISSUE THREAD

**Issue by wangat2001** [S2U2MLancer/robot#2]
目标，功能，roadmap
-- 产出 wiki,  milestone

**Comment by xiayy860612** [comment]
robot框架，你指的是[robot framework](http://robotframework.org/)？

**Comment by wangat2001** [comment]
@share2u2m  
PomeloRobot https://github.com/NetEase/pomelo-robot
我看了一下，他的针对性非常强，只针对pomelo框架的服务器，但是他提供的功能和思路值得参考。

**Comment by xiayy860612** [comment]
有个参考的例子：https://github.com/NetEase/pomelo-robot-demo
我们是参考pomelo-robot，用robot framework来做吗？

**Comment by wangat2001** [comment]
不是，只是边做边找方向和需求。我们的目标：
- 针对游戏服务器的性能测试工具。
- 明确的项目，练习远程协作。

我的想法是，分析一下市场上其它产品，发现我们的需求。

**Comment by xiayy860612** [comment]
@wangat2001 了解。

那我提提我目前遇到的一些场景和基本需求哈：

- 支持robot无交互性测试，测试无玩家交互性的业务逻辑
- 支持robot无交互性的压力测试，即支持单机多robot及多机多无交互robots
- 收集从客户端得到的同服务器交互相关的性能数据
- 测试框架和测试脚步分离，尽量保证测试脚步的可重用性以及易书写

进阶需求：

- 支持多robot的交互性测试，相对复杂逻辑的交互性测试，
尤其是在支持MMO类型的游戏时非常需要，
这个过去我在我第一家游戏公司时见到过，公司老总自己开发的一套。
这个难度有点高，因为还涉及到一定的AI功能。
- 支持分布式测试，可参考[pomelo-robot](https://github.com/NetEase/pomelo/wiki/PomeloRobot-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)以及redis的架构，![pomelo-robot基础架构](https://camo.githubusercontent.com/c39083c4053b86c23e9bcaba71608e2233583a4a/68747470733a2f2f7261772e6769746875622e636f6d2f70616c6d746f792f496d6167654275636b65742f6d61737465722f506f6d656c6f2f526f626f742f312e6a7067)
- 收集服务器端的性能

**Comment by wangat2001** [comment]
@share2u2m 
交互性那个有点难，其它我都赞成。需求讨论先到这里。我们先把基本的无交换的测试框架这块实现。
暂时补充以下：
- 支持高压，定时长的测试
- 支持定制场景测试
- 如果某一个robot死掉，能自动重启并发送一报告

@swolicetax @share2u2m 
需求整理如下：
ref: https://github.com/S2U2MLancer/robot/wiki/%E5%8F%91%E7%8E%B0%E9%9C%80%E6%B1%82
